GymFitApplication/Controllers/ProductController.cs
using GymFitApplication.Data;
using GymFitApplication.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Amazon; //for linking your AWS account
using Amazon.S3;
using Amazon.S3.Model;

namespace GymFitApplication.Controllers
{
    public class ProductController : Controller
    {
        private readonly GymFitApplicationContext _context;
		private const string s3BucketName = "gymfitapplication";

		private List<string> getKeys()
		{
			//create an empty list
			List<string> keys = new List<string>();

			//1. link to appsettings.json and get back the values
			var builder = new ConfigurationBuilder()
							.SetBasePath(Directory.GetCurrentDirectory())
							.AddJsonFile("appsettings.json");
			IConfigurationRoot configure = builder.Build(); //build the json file

			//2. read the info from json using configure instance
			keys.Add(configure["Values:Key1"]);
			keys.Add(configure["Values:Key2"]);
			keys.Add(configure["Values:Key3"]);

			return keys;
		}

		public ProductController(GymFitApplicationContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        // Create Product
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Create(Product product, List<IFormFile> imagefiles)
        {
            if (ModelState.IsValid)
            {
				List<string> keys = getKeys();
				var awsS3client = new AmazonS3Client(keys[0], keys[1], keys[2], RegionEndpoint.USEast1);

                string imageUrl = null;

                //2. read image by image and store to S3
                foreach (var image in imagefiles)
				{
					if (image.Length <= 0)
					{
						TempData["ImageUploadErrorMessage"] = "It is an empty file. Unable to upload!";
						return View("Index",product);
					}
					else if (image.Length > 2048576) //not more than 2MB
					{
						TempData["ImageUploadErrorMessage"] = "It is over 2MB limit of size. Unable to upload!";
                        return View("Index", product);
                    }
					else if (image.ContentType.ToLower() != "image/png" &&
						image.ContentType.ToLower() != "image/jpeg"
						&& image.ContentType.ToLower() != "image/gif") //not valid image reject also
					{
						TempData["ImageUploadErrorMessage"] = "It is not a valid image! Unable to upload!";
                        return View("Index", product);
                    }

					//3. upload image to S3 and get the URL
					try
					{
						//upload to S3
						PutObjectRequest uploadRequest = new PutObjectRequest //generate the request
						{
							InputStream = image.OpenReadStream(),
							BucketName = s3BucketName,
							Key = "images/" + image.FileName,
							CannedACL = S3CannedACL.PublicRead
						};

						//send out the request
						await awsS3client.PutObjectAsync(uploadRequest);

                        imageUrl = $"https://{s3BucketName}.s3.amazonaws.com/images/{image.FileName}";
                    }
					catch (AmazonS3Exception ex)
					{
						TempData["ImageUploadErrorMessage"] = ("Unable to upload to S3 due to technical issue. Error message: " + ex.Message);
                        return View("Index", product);
                    }
					catch (Exception ex)
					{
						TempData["ImageUploadErrorMessage"] = ("Unable to upload to S3 due to technical issue. Error message: " + ex.Message);
                        return View("Index", product);
                    }

				}

                product.Image = imageUrl;
                _context.ProductTable.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction("ProductList");
            }
            return View("Index", product);
        }

        // View Product
        public async Task<IActionResult> ProductList(string? msg)
        {
            string cloudfrontdomain = "https://d3svoy2tv8bd04.cloudfront.net/";
            //Get user list from db table
            List<Product> productList
                = await _context.ProductTable.ToListAsync();
            
            foreach(var product in productList)
            {
                if(product.Image != null)
                {
                    string imageUrl = product.Image;
                    var uri = new Uri(imageUrl);
                    var imageKey = uri.PathAndQuery.TrimStart('/');
                    product.Image = cloudfrontdomain + imageKey;
                }  
            }                     

            return View(productList);
        }

        // Delete Product
        public async Task<IActionResult> deletepage(int? productid)
        {
            if (productid == null)
            {
                return BadRequest("Error: Product ID is not exists!");
            }

            var product = await _context.ProductTable.FindAsync(productid);

            if (product == null)
            {
                return BadRequest("Error: Not Product in the database!");
            }

            if(product.Image != null)
            {
                string imageUrl = product.Image;
                var uri = new Uri(imageUrl);
                var imageKey = uri.PathAndQuery.TrimStart('/');

                List<string> keys = getKeys();
                var awsS3client = new AmazonS3Client(keys[0], keys[1], keys[2], RegionEndpoint.USEast1);

                try
                {
                    DeleteObjectRequest request = new DeleteObjectRequest
                    {
                        BucketName = s3BucketName,
                        Key = imageKey
                    };
                    await awsS3client.DeleteObjectAsync(request);

                }
                catch (AmazonS3Exception ex)
                {
                    return BadRequest(ex.Message);
                }
            }

            _context.ProductTable.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction("ProductList", new
            {
                msg = "Product with id" + productid
                + "is removed from database!"
            });
        }

        //Edit Product
        public async Task<IActionResult> editpage(int? productid)
        {
            //Check id
            if (productid == null)
            {
                return NotFound();
            }

            var product = await _context.ProductTable.FindAsync(productid);

            //Check product
            if (product == null)
            {
                return NotFound();
            }

            //Redirect to edit page
            return View(product);
        }

        // Update Product
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> updatepage(Product product, List<IFormFile> imagefiles)
        {
            if (ModelState.IsValid)
            {
                List<string> keys = getKeys();
                var awsS3client = new AmazonS3Client(keys[0], keys[1], keys[2], RegionEndpoint.USEast1);

                string imageUrl = null;

                //2. read image by image and store to S3
                foreach (var image in imagefiles)
                {
                    if (image.Length <= 0)
                    {
                        return BadRequest("It is an empty file. Unable to upload!");
                    }
                    else if (image.Length > 1048576) //not more than 1MB
                    {
                        return BadRequest("It is over 1MB limit of size. Unable to upload!");
                    }
                    else if (image.ContentType.ToLower() != "image/png" &&
                        image.ContentType.ToLower() != "image/jpeg"
                        && image.ContentType.ToLower() != "image/gif") //not valid image reject also
                    {
                        return BadRequest("It is not a valid image! Unable to upload!");
                    }

                    //3. upload image to S3 and get the URL
                    try
                    {
                        //upload to S3
                        PutObjectRequest uploadRequest = new PutObjectRequest //generate the request
                        {
                            InputStream = image.OpenReadStream(),
                            BucketName = s3BucketName,
                            Key = "images/" + image.FileName,
                            CannedACL = S3CannedACL.PublicRead
                        };

                        //send out the request
                        await awsS3client.PutObjectAsync(uploadRequest);

                        imageUrl = $"https://{s3BucketName}.s3.amazonaws.com/images/{image.FileName}";
                    }
                    catch (AmazonS3Exception ex)
                    {
                        return BadRequest("Unable to upload to S3 due to technical issue. Error message: " + ex.Message);
                    }
                    catch (Exception ex)
                    {
                        return BadRequest("Unable to upload to S3 due to technical issue. Error message: " + ex.Message);
                    }

                }

                product.Image = imageUrl;

                var existingProduct = await _context.ProductTable.FindAsync(product.ProductId);

                if (existingProduct != null)
                {
                    existingProduct.Name = product.Name;
                    existingProduct.Description = product.Description;
                    existingProduct.Price = product.Price;
                    if(product.Image != null)
                    {
                        existingProduct.Image = product.Image;
                    }                    

                    _context.ProductTable.Update(existingProduct);
                    await _context.SaveChangesAsync();

GymFitApplication/Controllers/TutorController.cs
using Amazon.S3.Model;
using Amazon.S3;
using GymFitApplication.Data;
using GymFitApplication.Models;
using Microsoft.AspNetCore.Mvc;
using Amazon; //for linking your AWS account
using Microsoft.EntityFrameworkCore;

namespace GymFitApplication.Controllers
{
    public class TutorController : Controller
    {
        private readonly GymFitApplicationContext _context;
        private const string s3BucketName = "gymfitapplication";

        private List<string> getKeys()
        {
            //create an empty list
            List<string> keys = new List<string>();

            //1. link to appsettings.json and get back the values
            var builder = new ConfigurationBuilder()
                            .SetBasePath(Directory.GetCurrentDirectory())
                            .AddJsonFile("appsettings.json");
            IConfigurationRoot configure = builder.Build(); //build the json file

            //2. read the info from json using configure instance
            keys.Add(configure["Values:Key1"]);
            keys.Add(configure["Values:Key2"]);
            keys.Add(configure["Values:Key3"]);

            return keys;
        }

        public TutorController(GymFitApplicationContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> editpage(string? tutorid)
        {
            //Check id
            if (tutorid == null)
            {
                return NotFound();
            }

            var tutor = await _context.TutorTable.FindAsync(tutorid);

            //Check tutor
            if (tutor == null)
            {
                return NotFound();
            }

            //Redirect to edit page
            return View(tutor);
        }

        // Update Tutor
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> updatepage(Tutor tutor, List<IFormFile> imagefiles)
        {
            if (ModelState.IsValid)
            {
                List<string> keys = getKeys();
                var awsS3client = new AmazonS3Client(keys[0], keys[1], keys[2], RegionEndpoint.USEast1);

                string imageUrl = null;

                //2. read image by image and store to S3
                foreach (var image in imagefiles)
                {
                    if (image.Length <= 0)
                    {
                        TempData["ImageUploadErrorMessage"] = "It is an empty file. Unable to upload!";
                        return View("editpage", tutor);
                    }
                    else if (image.Length > 1048576) //not more than 1MB
                    {
                        TempData["ImageUploadErrorMessage"] = "It is over 2MB limit of size. Unable to upload!";
                        return View("editpage", tutor);
                    }
                    else if (image.ContentType.ToLower() != "image/png" &&
                        image.ContentType.ToLower() != "image/jpeg"
                        && image.ContentType.ToLower() != "image/gif") //not valid image reject also
                    {
                        TempData["ImageUploadErrorMessage"] = "It is not a valid image! Unable to upload!";
                        return View("editpage", tutor);
                    }

                    //3. upload image to S3 and get the URL
                    try
                    {
                        //upload to S3
                        PutObjectRequest uploadRequest = new PutObjectRequest //generate the request
                        {
                            InputStream = image.OpenReadStream(),
                            BucketName = s3BucketName,
                            Key = "images/" + image.FileName,
                            CannedACL = S3CannedACL.PublicRead
                        };

                        //send out the request
                        await awsS3client.PutObjectAsync(uploadRequest);

                        imageUrl = $"https://{s3BucketName}.s3.amazonaws.com/images/{image.FileName}";
                    }
                    catch (AmazonS3Exception ex)
                    {
                        TempData["ImageUploadErrorMessage"] = ("Unable to upload to S3 due to technical issue. Error message: " + ex.Message);
                        return View("editpage", tutor);
                    }
                    catch (Exception ex)
                    {
                        TempData["ImageUploadErrorMessage"] = ("Unable to upload to S3 due to technical issue. Error message: " + ex.Message);
                        return View("editpage", tutor);
                    }

                }

                tutor.Image = imageUrl;

                var existingTutor = await _context.TutorTable.FindAsync(tutor.Id);

                if (existingTutor != null)
                {                     
                    existingTutor.Description = tutor.Description;
                    existingTutor.Title = tutor.Title;

                    if (tutor.Image != null)
                    {
                        existingTutor.Image = tutor.Image;
                    }

                    _context.TutorTable.Update(existingTutor);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("TutorList");
                }
            }

            return View("editpage", tutor);
        }

        //Display tutorList in Management Section
        public async Task<IActionResult> TutorList(string? msg)
        {
            //Get tutor list from db table
            List<Tutor> tutorList
                = await _context.TutorTable.ToListAsync();

            return View(tutorList);
        }

        //Display tutorList in public view
        public async Task<IActionResult> ViewTutor()
        {
            //Get tutor list from db table
            List<Tutor> tutorList
                = await _context.TutorTable.ToListAsync();

            return View(tutorList);
        }

		public IActionResult Search(string searchString)
		{
			if (searchString != null)
			{
				List<Tutor> tutors = _context.TutorTable
				.Where(u => u.Name.Contains(searchString) || u.Title.Contains(searchString) || u.Description.Contains(searchString))
				.ToList();

				return View("TutorList", tutors);
			}

			List<Tutor> alltutors = _context.TutorTable.ToList();
			return View("TutorList", alltutors);
		}

		public async Task<IActionResult> deletepage(string? tutorid)
		{
			if (tutorid == null)
			{
				return BadRequest("Error: Tutor ID is not exists!");
			}

			var tutor = await _context.TutorTable.FindAsync(tutorid);

			if (tutor == null)
			{
				return BadRequest("Error: Not Tutor in the database!");
			}

            if(tutor.Image != null)
            {
                string imageUrl = tutor.Image;
                var uri = new Uri(imageUrl);
                var imageKey = uri.PathAndQuery.TrimStart('/');

                List<string> keys = getKeys();
                var awsS3client = new AmazonS3Client(keys[0], keys[1], keys[2], RegionEndpoint.USEast1);

                try
                {
                    DeleteObjectRequest request = new DeleteObjectRequest
                    {
                        BucketName = s3BucketName,
                        Key = imageKey
                    };
                    await awsS3client.DeleteObjectAsync(request);

                }
                catch (AmazonS3Exception ex)
                {
                    return BadRequest(ex.Message);
                }
            }
			
			_context.TutorTable.Remove(tutor);
			await _context.SaveChangesAsync();
			return RedirectToAction("TutorList", new
			{
				msg = "Product with id" + tutorid
				+ "is removed from database!"
			});
		} 
	}
}

GymFitApplication/Views/Tutor/TutorList.cshtml
@model IEnumerable<GymFitApplication.Models.Tutor>

@{
    ViewData["Title"] = "TutorList";
}


<style>
    button {
        background-color: rgb(245, 99, 75);
        border: 0;
        color: white;
    }
</style>

<h3>@ViewData["Title"]</h3>

<center style="margin-top:80px; margin-bottom:50px">
    <div class="row">
        <div class="col-4">
            <form method="post" asp-action="Search" asp-controller="Tutor">
                <label>Keyword</label> &nbsp;&nbsp;
                <input type="text" name="SearchString" /> &nbsp;&nbsp;
                <button type="submit">Search</button>
            </form>
        </div>
        <div class="col-4">
            <h1>Tutor List</h1>
        </div>
        @*<div class="col-4">
            <a class="nav-link" asp-action="Index" asp-controller="Product">
                <button class="btn-lg">New Tutor</button>
            </a>
        </div>*@
    </div>


    <div style="padding:20px 50px">
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Title</th>
                    <th>Image</th>
                    <th>Action</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var tutor in Model)
                {
                    <tr>
                        <td>@tutor.Name</td>
                        <td>@tutor.Description</td>
                        <td>@tutor.Title</td>
                        @if(@tutor.Image != null){
                            <td><img src="@tutor.Image" width="200" height="200" /></td>
                        }
                        else
                        {
                            <td>@tutor.Image</td>
                        }
                        <td><a asp-action="editpage" asp-controller="Tutor" asp-route-tutorid="@tutor.Id"><button>Edit</button></a></td>
                        <td><a asp-action="deletepage" asp-controller="Tutor" asp-route-tutorid="@tutor.Id"><button>Delete</button></a></td>
                    </tr>                                  
                }
            </tbody>
        </table>
    </div>
</center>

GymFitApplication/Views/Tutor/ViewTutor.cshtml
@model List<Tutor>

@{
    ViewData["Title"] = "ViewTutor";
}

<div class="main-wrapper ">
	<section class="page-title bg-2">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 text-center">
					<ul class="list-inline mb-0">
						<li class="list-inline-item"><a asp-controller="Home" asp-action="Index" class="text-sm letter-spacing text-white text-uppercase font-weight-bold">Home</a></li>
						<li class="list-inline-item"><span class="text-white">|</span></li>
						<li class="list-inline-item"><a href="#" class="text-color text-uppercase text-sm letter-spacing">Tutor</a></li>
					</ul>
					<h1 class="text-lg text-white mt-2">Tutor</h1>
				</div>
			</div>
		</div>
	</section>

	<!-- Section Team Start -->
	<section class="section bg-gray">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-lg-8 text-center">
					<div class="section-title">
						<div class="divider mb-3"></div>
						<h2>Our Tutor</h2>
					</div>
				</div>
			</div>

			<div class="row">
				@foreach (var tutor in Model)
				{
					<div class="col-lg-6">
						<div class="card border-0 mb-1  bg-transparent rounded-0 mb-4">
							<div class="row no-gutters align-items-center">
								<div class="col-md-6">
									<img src="@tutor.Image" alt="" class="img-fluid w-100">
								</div>
								<div class="col-md-6">
									<div class="card-body team-wrap pl-4">
										<h3 class="card-title text-color">@tutor.Name</h3>
										<h6 class="card-subtitle pb-4 letter-spacing">@tutor.Title</h6>
										<p class="mb-5">@tutor.Description</p>
									</div>
								</div>
							</div>
						</div>
					</div>
				}		
			</div>
		</div>
	</section>

GymFitApplication/Views/Tutor/editpage.cshtml
@model GymFitApplication.Models.Tutor

@{
    ViewData["Title"] = "editpage";
}

<h3>@ViewData["Title"]</h3>

<center style="margin-top:80px; margin-bottom:50px">
    <style="padding:0px 10px">
        <form method="post" asp-action="updatepage" asp-controller="Tutor" style="margin:auto;text-align:left;max-width:600px" enctype="multipart/form-data">
            <h2>Edit Tutor</h2>
            @{
                var ImageUploadErrorMessage = TempData["ImageUploadErrorMessage"] as string;
            }

            @if (!string.IsNullOrEmpty(ImageUploadErrorMessage))
            {
                <div class="alert alert-danger">
                    @ImageUploadErrorMessage
                </div>
            }
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" readonly/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label">Image</label>
                <div class="row justify-content-center">
                    @if (!string.IsNullOrEmpty(Model.Image))
                    {
                        <img src="@Model.Image" alt="Product Image" class="img-fluid" width="200px" height="200px" />
                    }
                </div>
                <input type="file" name="imagefiles" accept="image/*" class="form-control pb-5 pt-3" />
            </div>
            <br />
            <button class="w-100 btn btn-lg btn-primary" style="background-color:rgb(245, 99, 75)">Save</button>
        </form>
    </div>
</center>