GymFitApplication/Controllers/AnnouncementController.cs
using Microsoft.AspNetCore.Mvc;
using Amazon;
using Amazon.SimpleNotificationService;
using Amazon.SimpleNotificationService.Model;

namespace GymFitApplication.Controllers
{
    public class AnnouncementController : Controller
    {
        private const string announcementTopicARN = "arn:aws:sns:us-east-1:717071075544:SNSAnnouncementNotification";

        //function 1: to get back the amazon account keys
        private List<string> getKeys()
        {
            //create an empty list
            List<string> keys = new List<string>();

            //link to appsettings.json and get back the values
            var builder = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("appsettings.json");

            IConfiguration configure = builder.Build(); //build the json file

            //no error
            keys.Add(configure["Values:key1"]); //get key 1
            keys.Add(configure["Values:key2"]); //get key 2
            keys.Add(configure["Values:key3"]); //get key 3

            return keys;
        }

        public IActionResult AnnouncementPage(string msg)
        {
            ViewBag.msg = msg;
            return View();
        }


        public async Task<IActionResult> processBroadcast(string subjecttitle, string msgBody)
        {
            if (subjecttitle == null || msgBody == null)
            {
                return RedirectToAction(nameof(AnnouncementPage), new { msg = "Error" });
            }

            List<string> keys = getKeys();
            AmazonSimpleNotificationServiceClient agent = new AmazonSimpleNotificationServiceClient(keys[0], keys[1], keys[2], RegionEndpoint.USEast1);

            try
            {
                PublishRequest request = new PublishRequest
                {
                    TopicArn = announcementTopicARN,
                    Subject = subjecttitle,
                    Message = msgBody
                };

                await agent.PublishAsync(request);
                return RedirectToAction(nameof(AnnouncementPage), new { msg = "Message is successfully broadcasted!" });
            }
            catch (AmazonSimpleNotificationServiceException ex)
            {
                return BadRequest(ex.Message);
            }
        }
    }
}

GymFitApplication/Views/Announcement/AnnouncementPage.cshtml
@{
    ViewData["Title"] = "AnnouncementPage";
}

<div style="text-align:left;margin-top:120px;margin-bottom:50px">
    <div style="padding:0px 10px">
        <form asp-action="processBroadcast" asp-controller="Announcement" style="max-width:600px;margin:auto">
            <h2>Newsletter & Announcement</h2>
            @if (!string.IsNullOrEmpty(@ViewBag.msg as string))
            {
                @if(@ViewBag.msg == "Error")
                {
                    <div id="statusMessage" class="alert alert-danger" role="alert">
                        Please fill in all fields!
                    </div>
                }
                else
                {
                    <div id="statusMessage" class="alert alert-success" role="alert">
                        @ViewBag.msg
                    </div>
                }

            }
            <hr />
            <div class="form-floating">
                <label>Subject Title:</label>
                <input type="text" name="subjecttitle" placeholder="Gym Reopening Notice" class="form-control" aria-required="true" />
            </div>
            <br />
            <div class="form-floating">
                <label>Message</label>
                <textarea name="msgBody" class="form-control" aria-required="true" rows="6" placeholder="Type something here ..."></textarea>
            </div>
            <br />
            <button id="submitForm" type="submit" class="w-100 btn btn-lg" style="background-color:rgb(245, 99, 75)">Broadcast Message</button>
        </form>
    </div>
</div>


<script>
    // Check if the status message is present, then set a timer to hide it after 5 seconds
    document.addEventListener("DOMContentLoaded", function() {
        var statusMessageElement = document.getElementById("statusMessage");
        if (statusMessageElement) {
            setTimeout(function() {
                statusMessageElement.style.display = "none";
            }, 5000); // 5000 milliseconds = 5 seconds
        }
    });
</script>