GymFitApplication/Controllers/PackageController.cs
using GymFitApplication.Areas.Identity.Data;
using GymFitApplication.Data;
using GymFitApplication.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NuGet.Packaging;

namespace GymFitApplication.Controllers
{
	public class PackageController : Controller
	{
		private readonly GymFitApplicationContext _context;
		private readonly UserManager<GymFitApplicationUser> _userManager;

		public PackageController(GymFitApplicationContext context, UserManager<GymFitApplicationUser> userManager)
		{
			_context = context;
            _userManager = userManager;
		}

		public IActionResult Index()
		{
			return View();
		}


        //Create Package
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Create(Package package)
		{            
			if (ModelState.IsValid)
			{
				_context.PackageTable.Add(package);
				await _context.SaveChangesAsync();
				return RedirectToAction("PackageList");
			}				
			return View(package);
		}

        //View package
        public async Task<IActionResult> PackageList(string? msg)
		{
			//Get user list from db table
			List<Package> packagelist
				= await _context.PackageTable.ToListAsync();

			ViewBag.msg = msg;

			return View(packagelist);
		}

        //Delete package
        public async Task<IActionResult> deletepage(int? packageid)
        {
            if (packageid == null)
            {
                return BadRequest("Error: User ID is not exists!");
            }

            var package = await _context.PackageTable.FindAsync(packageid);

            if (package == null)
            {
                return BadRequest("Error: Not user in the database!");
            }

            _context.PackageTable.Remove(package);
            await _context.SaveChangesAsync();
            return RedirectToAction("PackageList", new
            {
                msg = "Package with id" + packageid
                + "is deleted from database!"
            });
        }

        //Edit package
        public async Task<IActionResult> editpage(int? packageid)
        {
            //Check id
            if (packageid == null)
            {
                return NotFound();
            }

            var package = await _context.PackageTable.FindAsync(packageid);

            //Check user
            if (package == null)
            {
                return NotFound();
            }

            //Redirect to edit page
            return View(package);

        }

        //Update package
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> updatepage(Package package)
        {
            if (ModelState.IsValid)
            {
                var existingPackage = await _context.PackageTable.FindAsync(package.PackageId);

                if (existingPackage != null)
                {
                    existingPackage.Name = package.Name;
                    existingPackage.Description = package.Description;
                    existingPackage.Price = package.Price;
                    existingPackage.Duration = package.Duration;
                    existingPackage.UserId = package.UserId;

                    _context.PackageTable.Update(existingPackage);
                    await _context.SaveChangesAsync();

                    List<Package> allpackages = _context.PackageTable.ToList();
                    return View("PackageList", allpackages);
                }
            }

            return View("editpage", package);
        }

        //Search user
        public IActionResult Search(string searchString)
        {
            if (searchString != null)
            {
                List<Package> packages = _context.PackageTable
                .Where(u => u.Name.Contains(searchString) || u.Description.Contains(searchString))
                .ToList();

                return View("PackageList", packages);
            }

            List<Package> allpackages = _context.PackageTable.ToList();
            return View("PackageList", allpackages);
        }

		public async Task<IActionResult> ViewPackage()
		{
			//Get user list from db table
			List<Package> packagelist
				= await _context.PackageTable.ToListAsync();

			return View(packagelist);
		}

        public async Task<IActionResult> Subscribe(int packageid)
        {
			if (User.Identity.IsAuthenticated)
            {
				//Get Current User
				var currentUser = await _userManager.GetUserAsync(User);

				if (currentUser != null)
				{
					var selectedPackage = await _context.PackageTable.FindAsync(packageid);

					if (selectedPackage != null)
					{
						// Update the user's PackageId
						currentUser.Packageid = packageid;
						_context.GymFitApplicationUsers.Update(currentUser);
						await _context.SaveChangesAsync();

						TempData["SubscriptionSuccessMessage"] = "Subsribe Package Sucessfully!";

						return RedirectToAction("ViewPackage");
					}
				}				
			}
			TempData["NotAuthenticatedMessage"] = "Please login to the account to subsribe!";
			return RedirectToAction("ViewPackage");
		}
	}
}

GymFitApplication/Controllers/TutorController.cs
using Amazon.S3.Model;
using Amazon.S3;
using GymFitApplication.Data;
using GymFitApplication.Models;
using Microsoft.AspNetCore.Mvc;
using Amazon; //for linking your AWS account
using Microsoft.EntityFrameworkCore;

namespace GymFitApplication.Controllers
{
    public class TutorController : Controller
    {
        private readonly GymFitApplicationContext _context;
        private const string s3BucketName = "gymfitapplication";

        private List<string> getKeys()
        {
            //create an empty list
            List<string> keys = new List<string>();

            //1. link to appsettings.json and get back the values
            var builder = new ConfigurationBuilder()
                            .SetBasePath(Directory.GetCurrentDirectory())
                            .AddJsonFile("appsettings.json");
            IConfigurationRoot configure = builder.Build(); //build the json file

            //2. read the info from json using configure instance
            keys.Add(configure["Values:Key1"]);
            keys.Add(configure["Values:Key2"]);
            keys.Add(configure["Values:Key3"]);

            return keys;
        }

        public TutorController(GymFitApplicationContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> editpage(string? tutorid)
        {
            //Check id
            if (tutorid == null)
            {
                return NotFound();
            }

            var tutor = await _context.TutorTable.FindAsync(tutorid);

            //Check tutor
            if (tutor == null)
            {
                return NotFound();
            }

            //Redirect to edit page
            return View(tutor);
        }

        // Update Tutor
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> updatepage(Tutor tutor, List<IFormFile> imagefiles)
        {
            if (ModelState.IsValid)
            {
                List<string> keys = getKeys();
                var awsS3client = new AmazonS3Client(keys[0], keys[1], keys[2], RegionEndpoint.USEast1);

                string imageUrl = null;

                //2. read image by image and store to S3
                foreach (var image in imagefiles)
                {
                    if (image.Length <= 0)
                    {
                        TempData["ImageUploadErrorMessage"] = "It is an empty file. Unable to upload!";
                        return View("editpage", tutor);
                    }
                    else if (image.Length > 1048576) //not more than 1MB
                    {
                        TempData["ImageUploadErrorMessage"] = "It is over 2MB limit of size. Unable to upload!";
                        return View("editpage", tutor);
                    }
                    else if (image.ContentType.ToLower() != "image/png" &&
                        image.ContentType.ToLower() != "image/jpeg"
                        && image.ContentType.ToLower() != "image/gif") //not valid image reject also
                    {
                        TempData["ImageUploadErrorMessage"] = "It is not a valid image! Unable to upload!";
                        return View("editpage", tutor);
                    }

                    //3. upload image to S3 and get the URL
                    try
                    {
                        //upload to S3
                        PutObjectRequest uploadRequest = new PutObjectRequest //generate the request
                        {
                            InputStream = image.OpenReadStream(),
                            BucketName = s3BucketName,
                            Key = "images/" + image.FileName,
                            CannedACL = S3CannedACL.PublicRead
                        };

                        //send out the request
                        await awsS3client.PutObjectAsync(uploadRequest);

                        imageUrl = $"https://{s3BucketName}.s3.amazonaws.com/images/{image.FileName}";
                    }
                    catch (AmazonS3Exception ex)
                    {
                        TempData["ImageUploadErrorMessage"] = ("Unable to upload to S3 due to technical issue. Error message: " + ex.Message);
                        return View("editpage", tutor);
                    }
                    catch (Exception ex)
                    {
                        TempData["ImageUploadErrorMessage"] = ("Unable to upload to S3 due to technical issue. Error message: " + ex.Message);
                        return View("editpage", tutor);
                    }

                }

                tutor.Image = imageUrl;

                var existingTutor = await _context.TutorTable.FindAsync(tutor.Id);

                if (existingTutor != null)
                {                     
                    existingTutor.Description = tutor.Description;
                    existingTutor.Title = tutor.Title;

                    if (tutor.Image != null)
                    {
                        existingTutor.Image = tutor.Image;
                    }

                    _context.TutorTable.Update(existingTutor);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("TutorList");
                }
            }

            return View("editpage", tutor);
        }

        //Display tutorList in Management Section
        public async Task<IActionResult> TutorList(string? msg)
        {
            //Get tutor list from db table
            List<Tutor> tutorList
                = await _context.TutorTable.ToListAsync();

            return View(tutorList);
        }

        //Display tutorList in public view
        public async Task<IActionResult> ViewTutor()
        {
            //Get tutor list from db table
            List<Tutor> tutorList
                = await _context.TutorTable.ToListAsync();

            return View(tutorList);
        }

		public IActionResult Search(string searchString)
		{
			if (searchString != null)
			{
				List<Tutor> tutors = _context.TutorTable
				.Where(u => u.Name.Contains(searchString) || u.Title.Contains(searchString) || u.Description.Contains(searchString))
				.ToList();

				return View("TutorList", tutors);
			}

			List<Tutor> alltutors = _context.TutorTable.ToList();
			return View("TutorList", alltutors);
		}

		public async Task<IActionResult> deletepage(string? tutorid)
		{
			if (tutorid == null)
			{
				return BadRequest("Error: Tutor ID is not exists!");
			}

			var tutor = await _context.TutorTable.FindAsync(tutorid);

			if (tutor == null)
			{
				return BadRequest("Error: Not Tutor in the database!");
			}

            if(tutor.Image != null)
            {
                string imageUrl = tutor.Image;
                var uri = new Uri(imageUrl);
                var imageKey = uri.PathAndQuery.TrimStart('/');

                List<string> keys = getKeys();
                var awsS3client = new AmazonS3Client(keys[0], keys[1], keys[2], RegionEndpoint.USEast1);

                try
                {
                    DeleteObjectRequest request = new DeleteObjectRequest
                    {
                        BucketName = s3BucketName,
                        Key = imageKey
                    };
                    await awsS3client.DeleteObjectAsync(request);

                }
                catch (AmazonS3Exception ex)
                {
                    return BadRequest(ex.Message);
                }
            }
			
			_context.TutorTable.Remove(tutor);
			await _context.SaveChangesAsync();
			return RedirectToAction("TutorList", new
			{
				msg = "Product with id" + tutorid
				+ "is removed from database!"
			});
		} 
	}
}

GymFitApplication/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using GymFitApplication.Data;
using GymFitApplication.Areas.Identity.Data;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace GymFitApplication.Controllers
{
	public class UserController : Controller
	{
		private readonly GymFitApplicationContext _context;

		public UserController(GymFitApplicationContext context)
		{
			_context = context;
		}

		public IActionResult Index()
		{
			return View();
		}

		//View user list
		public async Task<IActionResult> UserList(string? msg)
		{
			//Get user list from db table
			List<GymFitApplicationUser> userlist
				= await _context.GymFitApplicationUsers.ToListAsync();

			ViewBag.msg = msg;

			return View(userlist);
		}

		public async Task<IActionResult> StudentList(string? msg)
		{
			List<GymFitApplicationUser> userlist = new List<GymFitApplicationUser>();
			var currentUser = await _context.GymFitApplicationUsers.FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);

			if (currentUser != null)
			{
				var package = await _context.PackageTable.FirstOrDefaultAsync(p => p.UserId == currentUser.Id);

				if (package != null)
				{
					userlist = _context.GymFitApplicationUsers.Where(user => user.Packageid == package.PackageId).ToList();
				}
				else
				{
					ViewBag.msg = "No student";
				}
			}

			return View(userlist);
		}

		//Delete user
		public async Task<IActionResult> deletepage(string? userid)
		{
			if (userid == null)
			{
				return BadRequest("Error: User ID is not exists!");
			}

			var user = await _context.GymFitApplicationUsers.FindAsync(userid);

			if (user == null)
			{
				return BadRequest("Error: Not user in the database!");
			}

			_context.GymFitApplicationUsers.Remove(user);
			await _context.SaveChangesAsync();
			return RedirectToAction("UserList", new
			{
				msg = "User with id" + userid
				+ "is deleted from database!"
			});
		}

		//Edit user
		public async Task<IActionResult> editpage(string? userid)
		{
			//Check id
			if (userid == null)
			{
				return NotFound();
			}

			var user = await _context.GymFitApplicationUsers.FindAsync(userid);

			//Check user
			if (user == null)
			{
				return NotFound();
			}

			//Redirect to edit page
			return View(user);

		}

		//Update user
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> updatepage(GymFitApplicationUser user)
		{
			if (ModelState.IsValid)
			{
				var existingUser = await _context.GymFitApplicationUsers.FindAsync(user.Id);

				if (existingUser != null)
				{
					existingUser.Dateofbirth = user.Dateofbirth;
					existingUser.PhoneNumber = user.PhoneNumber;
					existingUser.Gender = user.Gender;

					_context.GymFitApplicationUsers.Update(existingUser);
					await _context.SaveChangesAsync();

					List<GymFitApplicationUser> allusers = _context.GymFitApplicationUsers.ToList();
					return View("UserList", allusers);
				}
			}

			return View("editpage", user);
		}

		//Search user
		public IActionResult Search(string searchString)
		{
			if (searchString != null)
			{
				List<GymFitApplicationUser> users = _context.Users
				.Where(u => u.UserName.Contains(searchString) || u.Email.Contains(searchString) || u.Rolename.Contains(searchString))
				.ToList();

				return View("UserList", users);
			}

			List<GymFitApplicationUser> allusers = _context.GymFitApplicationUsers.ToList();
			return View("UserList", allusers);

		}

	}
}

GymFitApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
@*    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GymFitApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GymFitApplication.styles.css" asp-append-version="true" />*@

    <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="GYm,fitness,business,company,agency,multipurpose,modern,bootstrap4">
    
  <!-- theme meta -->
  <meta name="theme-name" content="gymfit" />
  
  <meta name="author" content="Themefisher.com">

  <title>GymTify</title>

  <!-- bootstrap.min css -->
  <link rel="stylesheet" href="~/theme/plugins/bootstrap/css/bootstrap.min.css">
  <!-- Icofont Css -->
  <link rel="stylesheet" href="~/theme/plugins/icofont/icofont.min.css">
  <!-- Themify Css -->
  <link rel="stylesheet" href="~/theme/plugins/themify/css/themify-icons.css">
  <!-- animate.css -->
  <link rel="stylesheet" href="~/theme/plugins/animate-css/animate.css">
  <!-- Magnify Popup -->
  <link rel="stylesheet" href="~/theme/plugins/magnific-popup/dist/magnific-popup.css">
  <!-- Owl Carousel CSS -->
  <link rel="stylesheet" href="~/theme/plugins/slick-carousel/slick/slick.css">
  <link rel="stylesheet" href="~/theme/plugins/slick-carousel/slick/slick-theme.css">
  <!-- Main Stylesheet -->
  <link rel="stylesheet" href="~/theme/css/style.css">
</head>
<body>
@*    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GymFitApplication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial"></partial>
                </div>
            </div>
        </nav>
    </header>*@
    <!-- Section Menu Start -->
    <!-- Header Start -->
    <nav class="navbar navbar-expand-lg navigation fixed-top" style="background-color:black" id="navbar">
	    <div class="container-fluid">
		    <a class="navbar-brand" asp-controller="Home" asp-action="Index">
			    <h2 class="text-white text-capitalize">Gym<span class="text-color">Tify</span></h2>
		    </a>
		    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsid"
			    aria-controls="navbarsid" aria-expanded="false" aria-label="Toggle navigation">
			    <span class="ti-view-list"></span>
		    </button>
		    <div class="collapse text-center navbar-collapse" id="navbarsid">
			    <ul class="navbar-nav mx-auto">
				    <li class="nav-item active">
					    <a class="nav-link" asp-controller="Home" asp-action="Index">Home <span class="sr-only">(current)</span></a>
				    </li>
				    <li class="nav-item dropdown">
					    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true"
						    aria-expanded="false">Pages.</a>
					    <ul class="dropdown-menu">
						    <li><a class="dropdown-item" asp-controller="Home" asp-action="About">About</a></li>
							<li><a class="dropdown-item" asp-action="ViewTutor" asp-controller="Tutor">Tutor</a></li>
							<li><a class="dropdown-item" asp-controller="Home" asp-action="Services">Services</a></li>
					    </ul>
				    </li>
				    <li class="nav-item"><a class="nav-link" asp-controller="Feedback" asp-action="ContactPage">Contact</a></li>
					<li class="nav-item">
						<a class="nav-link" asp-action="ViewPackage" asp-controller="Package">
							Package
						</a>
					</li>
					</li>
					<li class="nav-item">
						<a class="nav-link" asp-action="ViewProduct" asp-controller="Product">
							Product
						</a>
					</li>
					@if (User.IsInRole("Admin"))
					{
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true"
							   aria-expanded="false">Notification.</a>
							<ul class="dropdown-menu">
								<li>
									<a class="dropdown-item" asp-controller="Announcement" asp-action="AnnouncementPage">
										News
									</a>
								</li>
								<li>
									<a class="dropdown-item" asp-action="ViewFeedbackPage" asp-controller="Feedback">
										Feedback
									</a>
								</li>								
							</ul>
						</li>						
						<li class="nav-item">
							<a class="nav-link" asp-action="ViewBookingRequestPage" asp-controller="Booking">
								Booking Request
							</a>
						</li>					

						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true"
							   aria-expanded="false">Manage.</a>
							<ul class="dropdown-menu">
								<li>
									<a class="dropdown-item" asp-action="PackageList" asp-controller="Package">
										Manage Package
									</a>
								</li>
								<li>
									<a class="dropdown-item" asp-action="TutorList" asp-controller="Tutor">
										Manage Tutor
									</a>
								</li>
								<li>
									<a class="dropdown-item" asp-action="ProductList" asp-controller="Product">
										Manage Product
									</a>
								</li>
								<li>
									<a class="dropdown-item" asp-action="UserList" asp-controller="User">
										Manage User
									</a>
								</li>
							</ul>
						</li>

					}

					@if (User.IsInRole("Customer")){
						<li class="nav-item">
							<a class="nav-link" asp-controller="Booking" asp-action="MakeBookingPage">Booking</a>
						</li>
					}

					@if (User.IsInRole("Tutor"))
					{
						<li class="nav-item">
							<a class="nav-link" asp-action="StudentList" asp-controller="User">
								View Student
							</a>
						</li>
					}
			    </ul>
				<partial name="_LoginPartial"></partial>
		    </div>
	    </div>
    </nav>

    @RenderBody()

    <footer class="footer bg-black-50">
	<div class="container">
		<div class="row">
			<div class="col-lg-4 col-md-6 mb-5 mb-lg-0">
				<h2 class="text-white mb-4">GymTify</h2>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus illo ad quo sunt maiores, sint nostrum omnis eaque cumque dolorum.</p>

				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
			</div>
			

			<div class="col-lg-3 col-md-6 mb-5 mb-lg-0">
				<div class="footer-widget recent-blog">
					<h4 class="mb-4 text-white letter-spacing text-uppercase">Recents Posts</h4>
					<div>
						<a href="blog-single.html"class="text-white">Claritas est etiam processus dynamicus</a>
						<p class="text-sm mt-2 text-white-50">30 february 2019</p>
					</div>
					<div class="mt-4">
						<a href="blog-single.html"class="text-white">Claritas est etiam processus dynamicus</a>
						<p class="text-sm mt-2 text-white-50">30 february 2019</p>
					</div>

				</div>
			</div>
			<div class="col-lg-2 col-md-5 mb-5 mb-lg-0">
				<div class="footer-widget">
					<h4 class="mb-4 text-white letter-spacing text-uppercase">Quick Links</h4>
					<ul class="list-unstyled footer-menu lh-40 mb-0">
						<li><a asp-controller="Home" asp-action="About"><i class="ti-angle-double-right mr-2"></i>About Us</a></li>
						<li><a asp-controller="Home" asp-action="Services"><i class="ti-angle-double-right mr-2"></i>Services</a></li>
						<li><a href="pricing.html"><i class="ti-angle-double-right mr-2"></i>Membership</a></li>
						<li><a href="course.html"><i class="ti-angle-double-right mr-2"></i>Courses</a></li>
						<li><a asp-controller="Feedback" asp-action="ContactPage"><i class="ti-angle-double-right mr-2"></i>Contact us</a></li>
					</ul>
				</div>
			</div>
			<div class="col-lg-3 col-md-5">
				<div class="footer-widget">
					<h4 class="mb-4 text-white letter-spacing text-uppercase">Home location</h4>
					<p>Bukit Jalil, Jalan Teknologi Park, Malaysia</p>
					<span class="text-white">+6012 518 9992</span>
					<span class="text-white">gymtify@gmail.com</span>
				</div>
			</div>
		</div>

		<div class="row align-items-center mt-5 px-3 bg-black mx-1">
			<div class="col-lg-4">
				<p class="text-white mt-3">GymTify © 2023 , Theme By <span class="text-color">Group 26</span></p>
			</div>
			<div class="col-lg-6 ml-auto text-right">
				<ul class="list-inline mb-0 footer-socials">
					<li class="list-inline-item"><a href="https://www.facebook.com/themefisher"><i class="ti-facebook"></i></a></li>
					<li class="list-inline-item"><a href="https://twitter.com/themefisher"><i class="ti-twitter"></i></a></li>
					<li class="list-inline-item"><a href="https://github.com/themefisher/"><i class="ti-github"></i></a></li>
				</ul>
			</div>
		</div>
	</div>
</footer>


@*    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - GymFitApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@

    <!-- Main jQuery -->
   <script src="~/theme/plugins/jquery/jquery.js"></script>
   <!-- Bootstrap 4.3.1 -->
   <script src="~/theme/plugins/bootstrap/js/bootstrap.min.js"></script>
   <!-- Slick Slider -->
   <script src="~/theme/plugins/slick-carousel/slick/slick.min.js"></script>
   <!--  Magnific Popup-->
   <script src="~/theme/plugins/magnific-popup/dist/jquery.magnific-popup.min.js"></script>
   <!-- Form Validator -->
   <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/3.32/jquery.form.js"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.11.1/jquery.validate.min.js"></script>
   <!-- Google Map -->
   <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"></script>
   <script src="~/theme/plugins/google-map/gmap.js"></script>

   <script src="~/theme/js/script.js"></script>




   @* <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>*@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>